package persistence.configuration;

import java.lang.reflect.Method;

import persistence.annotation.Column;
import persistence.annotation.Id;
import persistence.exception.PersistenceException;


public class SimpleColumnProperty extends AbstractPersistentProperty {
	
	private static final String NOT_NULL = " NOT NULL";
	private static final String AUTO_GENERATED = " AUTO_INCREMENT";
	
	/*
	 * 
	 * Le nom de l'attribut, par exemple « title » pour Book La classe java
	 * de cet attribut Le nom de la colonne dans la table, par défaut le nom de
	 * l'attribut Le type SQL de la colonne, par exemple VARCHAR(255) true si la
	 * propriété est l'id
	 */
	
	private boolean id;
	private boolean autoGenerated;

	public SimpleColumnProperty(PersistentClass aPersistentClass, Method aMethod) throws PersistenceException {
		setOwner(aPersistentClass);
		setMethod(aMethod);
		parse(aPersistentClass);
	}

	public boolean isId() {
		return id;
	}

	public void setId(boolean id) {
		this.id = id;
	}

	public boolean isAutoGenerated() {
		return autoGenerated;
	}

	public void setAutoGenerated(boolean autoGenerated) {
		this.autoGenerated = autoGenerated;
	}

	public void parse(PersistentClass aPersistentClass) throws PersistenceException {
		String methodName = getMethod().getName();
		String propertyName = methodName.substring(3, 4).toLowerCase() + methodName.substring(4);
		setName(propertyName);
		Class<?> rclazz = getMethod().getReturnType();
		setClazz(rclazz);
		setId(false);
		rclazz = getClassOrWrapper();

		Column column = getMethod().getAnnotation(Column.class);
		if (column != null && 
			column.name().length() != 0  )
			setColumnName(column.name());
		else
			setColumnName(propertyName);

		if (column != null && column.type().length() != 0) {
			setSqlType(column.type());
		} else {
			setSqlType(getSqlTypeForClass(rclazz));
		}
		
		Id id = getMethod().getAnnotation(Id.class);
		if (id != null) {
			setId(true);
			setAutoGenerated(id.autoGenerated());
			aPersistentClass.setId(this);
			setSqlType(getSqlType()+NOT_NULL);
			if (isAutoGenerated()) {
				setSqlType(getSqlType()+AUTO_GENERATED);
			}
		}
	}

}
