/**
 * 
 */
package persistence.test.entity;

import java.util.List;

import persistence.annotation.Id;
import persistence.annotation.OneToMany;

/**
 * @author dga
 * 
 */
public class Category {
	private String title;
	private Long id;
	private List<Book> books;

	@Id(autoGenerated = true)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(mappedBy = "category", lazy = true)
	public List<Book> getBooks() {
		return books;
	}

	public void setBooks(List<Book> books) {
		this.books = books;
	}

}
